services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    environment:
      PORT: 3001
      SQLITE_DB: /app/data/app.db
      REDIS_URL: redis://redis:6379
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
    depends_on:
      redis:
        condition: service_started

  web:
    build:
      context: ./
      dockerfile: Dockerfile.web
    ports:
      - "5173:80"
    depends_on:
      api:
        condition: service_healthy

  redis:
    image: redis:7
    ports:
      - "6379:6379"
